### ISSUE TITLE
add mozilla certs by default

### ISSUE THREAD

**Issue by tanner0101** [vapor/tls#19]
Use mozilla's CA certificates by default for the client.

**Comment by tanner0101** [comment]
``` https://golang.org/src/crypto/x509/root_linux.go```

https://golang.org/src/crypto/x509/root_linux.go

Shows where certs on Linux are. None on macOS by default so maybe Mozilla certs should be used there.
```

**Comment by czechboy0** [comment]
It'd be great if we could get access to what the trusted certificates are on the Mac. Users already specify which certs to trust, in addition to the trusted by default ones. So it'd be useful to just take those from the keychain. I haven't looked into how/whether that's possible.

**Comment by tanner0101** [comment]
@edjiang was saying you can't without accessing the Keychain API :(

**Comment by edjiang** [comment]
I mean, there's no reason why you can't use the Keychain API with Swift... =]

**Comment by edjiang** [comment]
https://developer.apple.com/library/mac/documentation/Security/Reference/certifkeytrustservices/index.html#//apple_ref/c/func/SecTrustCopyAnchorCertificates

**Comment by czechboy0** [comment]
@edjiang Do you know if the keychain has to be unlocked at that moment? If not we should be able to use it easily.

**Comment by edjiang** [comment]
I'm fairly certain the keychain will allow things to read it the root CAs anytime... things like passwords, or editing the root CAs will probably need escalated privileges though.

**Comment by czechboy0** [comment]
Makes sense, do you want to look into pulling out the certificate files that we can plug into `TLS.Config`? It would be awesome to be able to provide the correct default certificates for each platform.

**Comment by tanner0101** [comment]
Using different certs on each platform could make the code less portable.
