### ISSUE TITLE
Bundle OpenSSL?

### ISSUE THREAD

**Issue by edjiang** [vapor/tls#6]
See https://github.com/Zewo/COpenSSL/issues/4

It doesn't seem like Zewo is as actively maintained anymore, so we might need to bundle OpenSSL into vapor/tls.

**Comment by paulofaria** [comment]
> It doesn't seem like Zewo is as actively maintained anymore, so we might need to bundle OpenSSL into vapor/tls.

Zewo is surely being maintained. Also, it's not possible to compile open ssl with SwiftPM. So it has to be a system package.

**Comment by edjiang** [comment]
Oops, sorry about that. I haven't seen many commits on Zewo projects recently so wrongfully assumed that. Let me close this issue.
