### ISSUE TITLE
SSL Handshake on macOS SIGABRT's

### ISSUE THREAD

**Issue by johnbona** [vapor/tls#61]
Using this example route:
```swift
router.get() { request -> Response in
	let googleClient = try request.make(Client.self)
	let google = try googleClient.get(URI("https://google.com")).await(on: request)

	print(google.http.body)

	return Response(http: HTTPResponse(status: .ok), using: request)
}
```
The TLS handshake crashes at `AppleTLSSocket.swift`, line 83:
```
malloc: *** error for object 0x101c23080: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

Using Swift 4.1 (1/30) and all packages are up to date (used `swift package update` not `vapor update`).

**Comment by gwynne** [comment]
The malloc error is due to using an `SSLContext` on more than one thread, which apparently `SecureTransport` doesn't like but also doesn't document anywhere that I can find. Fixing this results in a socket that fails to parse the HTTP request properly instead.

**Comment by tanner0101** [comment]
We have this example in unit tests now and is passing 👍. I believe this is related to a bug in `.await()` which has been fixed now. Either way, don't use `.await()` in route closures if possible.
