### ISSUE TITLE
Runtime error on Ubuntu 16.04

### ISSUE THREAD

**Issue by ADGrant** [vapor/tls#65]
When trying to run vapor on Ubuntu 16.04 with tls enabled, I get the following error:

Fatal error: Error raised at top level: Transport Layer Security Error: No such file or directory

Identifier: TLS.TLSError.SSL_CTX_use_PrivateKey_file (0): file /home/buildnode/jenkins/workspace/oss-swift-4.0-package-linux-ubuntu-16_04/swift/stdlib/public/core/ErrorType.swift, line 187
Current stack trace:
0    libswiftCore.so                    0x00007fd7e4d31cf0 _swift_stdlib_reportFatalErrorInFile + 221
1    libswiftCore.so                    0x00007fd7e4a37220 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 284
2    libswiftCore.so                    0x00007fd7e4cd7891 <unavailable> + 4155537
3    libswiftCore.so                    0x00007fd7e4cedf49 <unavailable> + 4247369
4    libswiftCore.so                    0x00007fd7e4a36afb <unavailable> + 1399547
5    libswiftCore.so                    0x00007fd7e4c505a9 <unavailable> + 3601833
6    libswiftCore.so                    0x00007fd7e4c8e68f <unavailable> + 3856015
7    libswiftCore.so                    0x00007fd7e4a36afb <unavailable> + 1399547
8    libswiftCore.so                    0x00007fd7e4bd0690 specialized _assertionFailure(_:_:file:line:flags:) + 144
9    libswiftCore.so                    0x00007fd7e4a846a0 swift_errorInMain + 371
10   JSONApiVape                        0x0000000000535809 <unavailable> + 1267721
11   libc.so.6                          0x00007fd7e2f7e740 __libc_start_main + 240
12   JSONApiVape                        0x000000000041e599 <unavailable> + 124313

The same settings work correctly on MacOS High Sierra.

**Comment by twof** [comment]
What's your Vapor version?

**Comment by ADGrant** [comment]
I am using 2.4.2.

**Comment by tanner0101** [comment]
> Transport Layer Security Error: No such file or directory

Double check that the directory your private key is referencing is correct.

**Comment by ADGrant** [comment]
I did find a typo in the private key file name, thanks. I do think the error reporting could be improved though. The error message is not particularly helpful and the stack trace was completely unnecessary.
